finalTable = processTransactions("TestPlayers.csv", "TestStocks.txt", "TestTransactions.csv");

function finalTable = processTransactions(playerFile, stockFile, transactionFile)
  % read player list
  pt = readtable(playerFile, "TextType","string");
  players = pt.email;
  % read stocks
  stocks = importdata(stockFile);
  % Set up cash and holdings
  cash = ones(numel(players), 1) * 10000;
  holdings = zeros(numel(players), numel(stocks));
  % Get stock prices.
  prices = hist_stock_data('01032024', now, stockFile);
  tickers = {prices.Ticker}; % Array of ticker symbols
  
  % Read transactions
  trans = importfile(transactionFile);

  % Remove time from transactions
  trans.Timestamp = dateshift(trans.Timestamp, 'start', 'day');
  for ii = 1:numel(trans.Timestamp)
    xaction = trans(ii, :);
    xtype = xaction.Type;
    xticker = xaction.Ticker;
    xdate = xaction.Timestamp;
    xplayer = xaction.EmailAddress;
    xshares = xaction.Shares;
    
    stockidx = xticker == stocks;
    xstock = prices(stockidx);
    dateidx = xdate == xstock.Date
    xprice = xstock.AdjClose(dateidx)
    xcash = xshares * xprice


    []
  end



end







function trans = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRANS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a timetable.
%
%  TRANS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  trans = importfile("/MATLAB Drive/MATLAB I/10 Stock Game Scorer Cell Arrays/TestDev/TestTransactions.csv", [2, Inf]);
%
%  See also READTIMETABLE.
%
% Auto-generated by MATLAB on 17-Apr-2024 15:41:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "EmailAddress", "Ticker", "Type", "Shares"];
opts.VariableTypes = ["datetime", "string", "categorical", "categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "EmailAddress", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EmailAddress", "Ticker", "Type"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Timestamp", "InputFormat", "MM/dd/yyyy HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
trans = readtimetable(filename, opts, "RowTimes", "Timestamp");

end